export const CREATE_MOVIE = 'CREATE_MOVIE';
/*export const CREATE_GENRE = 'CREATE_GENRE';
export const CREATE_CHOICE = 'CREATE_CHOICE';
export const CREATE_THEBEST = 'CREATE_THEBEST';
export const CREATE_RESULT = 'CREATE_RESULT';*/
export const CREATE_DETAIL = 'CREATE_DETAIL';
